<a href="https://colab.research.google.com/github/AqueeqAzam/numpy-for-mathematical-computing/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `Creating Arrays, and some basic operation`

In [ ]:
import numpy as np

# creating array

arr = np.array([23, 45, 23, 12])
arr

# check array types
type(arr)

# zeros array (fill array with zeros)
arr_zero = np.zeros(4)
arr_zero

# with multi dimension
arr_zero = np.zeros((3,4))
arr_zero

# ones array (fill array with zeros)
arr_ones = np.ones(4)
arr_ones

# empty array
arr_em = np.empty(4)
arr_em

# array range
arr_rn = np.arange(4)
arr_rn

# array dimgonal
arr_dig = np.eye(3, 5)
arr_dig

# array linespace
arr_lp = np.linspace(0, 20, num=5)
arr_lp

array([ 0.,  5., 10., 15., 20.])

# `Array with random numbers`

In [ ]:
# rand(): generate random value between 0 and 1

# randn(): generate random value close to 0

# ranf(): generate random value close to [0.0, 1.0]

# randint(): generate random number between 0 and 1

import numpy as np

var = np.random.rand(4)
var

var = np.random.rand(4)
var

var = np.random.randn(4)
var

min = 4
max = 90
tot_val = 5
var = np.random.randint(min, max, tot_val)
var

array([ 9, 54, 77, 16, 19])

# `Data Type`

In [ ]:
import numpy as np
var = np.array([1,2,3,4])
print("Data", var.dtype)

var = np.array([1.3,2.6,3.8,4.2])
print("Data", var.dtype)

var = np.array(['A', 'V', 'X'])
print("Data", var.dtype)

# converting datatypes
var = np.array([1,2,3,4], dtype = np.int8)
print("Data Type", var.dtype)

var = np.array([1,2,3,4], dtype = "f")
print("Data Type", var.dtype)
print(var)

# `Shape adn Size`

In [ ]:
import numpy as np

var = np.array([[1, 4], [3, 6]])
print(var)

# check dimension
print(var.shape)

# creating multidimension array
var1 = np.array([1, 3, 6, 8, 19], ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

# reshape array
var3 = np.array([1, 2, 3, 4, 5, 6])
x = var3.reshape(2, 3)
print(x)


var4 = np.array([1, 2, 3, 4, 5, 6])
x = var4.reshape(-1)
print(x)
print(x.ndim)



# `Array Slicing`

In [ ]:
# creating multidimension array
arr = np.array([[1, 4, 85, 45], [1, 14, 65, 45], [1, 4, 65, 5]])
arr

# slicing
arr = np.array([23, 56, 34, 22])
arr[0:3]
arr[2:3]

arr = np.array([[1, 4, 85, 45], [1, 14, 65, 45], [1, 4, 65, 5]])
arr[1, 2:4]

# `Inspecting an Array`

In [ ]:
import numpy as np

# creating array

arr = np.array([23, 45, 23, 12])
arr

# check array types
type(arr)

# creating multidimension array
arr = np.array([[1, 4, 85, 45], [1, 14, 65, 45], [1, 4, 65, 5]])
arr

# check dimension (no of array dim)
arr.ndim

# slicing
arr = np.array([23, 56, 34, 22])
arr[0:3]
arr[2:3]

arr = np.array([[1, 4, 85, 45], [1, 14, 65, 45], [1, 4, 65, 5]])
arr[1, 2:4]

# check size (no of array ele)
np.size(arr)



# checking length
len(arr)

# check data types
arr.dtype

arr.astype

(3, 4)


<function ndarray.astype>

# `Mathematical Operation`

In [ ]:
import numpy as np
arr1 = np.array([34, 54, 20, 45, 90])
arr2 = np.array([4, 4, 23, 15, 10])

# add elements
add_ele = arr1 + 3
print(add_ele)

# add two array
arr = arr1 + arr2
arr

# by using add function
arr_add = np.add(arr1, arr2)
arr_add

# by using subtract function
arr_sub = np.subtract(arr1, arr2)
arr_sub

# by using multiply function
arr_mul = np.multiply(arr1, arr2)
arr_mul

# by using subtract function
arr_div = np.divide(arr1, arr2)
arr_div



arr1 = np.array([[34, 54], [20, 45]])  # Modified to have consistent dimensions
arr2 = np.array([[4, 4], [23, 15]])    # Modified to have consistent dimensions
mul_dim_arr_add = np.add(arr1, arr2)
mul_dim_arr_add

# calculate power
arr1 = np.array([3, 5, 6, 8])
arr2 = np.array([3])
np.power(arr1, arr2)

# calculate squareroot
arr1 = np.array([27, 125, 16])
arr2 = np.sqrt(arr1)
arr2

# calculate square
arr1 = np.array([27, 125, 16])
arr2 = np.square(arr1)
arr2

# calculate square
arr1 = np.array([2, 5, 6])
arr2 = np.reciprocal(arr1)
print(arr2)

# calculate minimum
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.min(arr1)
arr2

# calculate maxinium
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.max(arr1)
arr2

# calculate minimum in 2 dim
arr1 = np.array([[2, 4, 6], [8, 10, 12]])
arr2 = np.min(arr1, axis=1)
arr2

# calculate minimum in 2 dim
arr1 = np.array([[2, 4, 6], [8, 10, 12]])
arr2 = np.min(arr1, axis=0)
arr2

# calculate trigonometry value
arr1 = np.array([0])
arr2 = np.sin(arr1)
arr2
arr3 = np.cos(arr1)
print(arr3)

# calculate minimum in 2 dim
arr1 = np.array([2, 4, 6])
arr2 = np.cumsum(arr1)
arr2



# `Boardcasting`

# `Copy and View`

In [ ]:
import numpy as np

arr = np.array([3, 6, 9, 12])
co = arr.copy()
arr[1] = 30
print('Original', arr)
print('Copy', co)

# view
vi = arr.view()
arr[1] = 40
print('Original', arr)
print('View', vi)

# `Combining and splitting array`

In [ ]:
import numpy as np

# concatenate array
arr1 = np.array([34, 67, 90])
arr2 = np.array([3, 6, 1])
arr3 = np.concatenate([arr1, arr2])
arr3

# concatenate array in 2-d
arr1 = np.array([[34, 7], [90, 1]])
arr2 = np.array([[3, 6], [1, 12]])

# concatnating 2-d array
arr3 = np.concatenate((arr1, arr2))
print(arr3)

# merging array
arr3 = np.concatenate((arr1, arr2), axis=1)
print(arr3)

# horizontal concatenation
hor_cat = np.hstack([arr1, arr2])
hor_cat

# vertical concatenation
ver_cat = np.vstack([arr1, arr2])
ver_cat

# spelliting array
a = np.array([34, 23, 2, 6, 8, 80, 34, 23, 12, 80])
b = np.array_split(a, 3)
print(b)

# `Add and Remove array`

In [ ]:
import numpy as np

# appending
arr = np.array([23, 90, 67, 8, 5, 8, 54])
np.append(arr, [50, 100])

# inserting
np.insert(arr, 1, [200, 300])


# Fix: Create an array with consistent row lengths
arr = np.array([[23, 90, 67], [8, 5, 8]])  # Removed the extra element from the second row
np.insert(arr, 1, [200, 300], axis=1)

# deleting
arr_del = np.array([23, 90, 67, 8, 5, 8, 54])
np.delete(arr_del, 1)

np.delete(arr_del, 1, axis=0)

array([23, 67,  8,  5,  8, 54])

# `Sraech, sort, filter`

In [ ]:
import numpy as np

arr = np.array([23, 90, 67, 8, 5, 8, 5])

# searchimh fun
arr_sea = np.where(arr == 67)

arr_sea = np.where(arr % 2 == 0)
print(arr_sea)

# search sorting fun
arr = np.array([23, 90, 67, 8, 5, 8, 5])
arr_sea_sort = np.searchsorted(arr, 8)
print(arr_sea_sort)

# sorting fun
arr = np.array([23, 90, 67, 8, 5, 8, 5])
arr_sort = np.sort(arr)
print(arr_sort)

# filter fun
arr = np.array([23, 90, 67])
f = [True, False, True]
new_arr = arr[f]
print(new_arr)


(array([1, 3, 5]),)
0
[ 5  5  8  8 23 67 90]
[23 67]


# `Arithmetic Functions`

In [ ]:
# shuffle function
import numpy as np
var = np.array([1, 2, 3, 4, 5])
np.random.shuffle(var)
print(var)

# unique function
var1 = np.array([1, 2, 3, 4, 5, 6, 3, 5, 2])
x = np.unique(var1)
print(x)

# size function
var2 = np.array([1, 2, 3, 4, 5, 6, 3, 5, 2])
x = np.size(var2)
print(x)

# resize function
var2 = np.array([1, 2, 3, 4, 5, 6, 3, 5, 2])
x = np.resize(var2, (3, 3))
print(x)

# flatten function
var2 = np.array([1, 2, 3, 4, 5, 6, 3, 5, 2])
x = np.resize(var2, (3, 2))
print(x.flatten(order='F'))


# `Matrix`

In [ ]:
import numpy as np
var = np.matrix([[1, 2], [4, 5]])
print(var)
print(type(var))

# transpose
var_t = np.transpose(var)
print(var_t)

# inverse
var_i = np.linalg.inv(var)
print(var_i)

# power
var_p = np.linalg.matrix_power(var, 2)
print(var_p)

# determinant
var_d = np.linalg.det(var)
print(var_d)

[[1 2]
 [4 5]]
<class 'numpy.matrix'>
[[1 4]
 [2 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[ 9 12]
 [24 33]]
-2.9999999999999996
